import numpy as np
marks = np.random.randint(0,101, (100,5))
print(marks[0:5])
avg_marks = np.mean(marks, axis=1)
print(f"The average marks of all subjects : {avg_marks[0:5]}")
highest_marks = np.max(marks, axis=1)
print(f"The highest marks in all subjects : {highest_marks[0:5]}")
lowest_marks = np.min(marks, axis=1)
print(f"The lowest marks in all subjects : {lowest_marks[0:5]}")
topper_per_subject = np.argmax(marks, axis=0)
print(f"The topper in each subject : {topper_per_subject[0:5]}")
topper_per_student = np.argmax(marks, axis=1)
print(f"The topper in each student : {topper_per_student[0:5]}")
topper_overall = np.argmax(avg_marks)
print(f"The overall topper is {topper_overall}")
grades = np.where(avg_marks >=80, 'A', np.where(avg_marks >=70, 'B', np.where(avg_marks >=60, 'C', np.where(avg_marks >=40, 'D', 'F'))))
print(grades[0:5])